### ISSUE TITLE
Does not support certificates signed with sha256

### ISSUE THREAD

**Issue by tfheen** [varnish/varnish-agent#1]
Seems like sha256-signed certs aren't properly supported:

$HOSTNAME /usr/sbin/varnish-agent: CALLER INFO  Call home result: 500 Can't connect to YYY:443 (SSL connect attempt failed with unknown errorerror:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm)

**Comment by huayra** [comment]
Agent deprecated. Check https://github.com/varnish/vagent2
