### ISSUE TITLE
**Security** SSL/HTTPS between vac and nodes

### ISSUE THREAD

**Issue by marme660** [varnish/varnish-agent#5]
call back url should support https.

**Comment by hugocruz** [comment]
I think this would be great !

**Comment by marme660** [comment]
specified the callback register url with https and it did not support:

LOGGER: http_run (modules/http.c:434): HTTP starting on port 6085
LOGGER: send_curl (modules/vac_register.c:78): Sending VAC registration request: https://10.0.2.2:8080/api/rest/register
LOGGER: issue_curl (modules/curl.c:130): Curl callback failed with status code 35

**Comment by daghf** [comment]
The varnish-agent2 repository is https://github.com/varnish/vagent2

I've opened an issue in the vagent2 repo: https://github.com/varnish/vagent2/issues/138
